config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'
  get '/second_task', to: 'dashboard#second_task', via: :get
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @start_point = 1.461
    @end_point = 4.0
  end

  def second_task

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def numbers_array(start_point, end_point, step)
    i = start_point
    num = end_point
    arr = []
    begin
      i = i.round(4)
      arr << i
      i += step
    end while i <= num
    arr
  end

  def fx_1(x)
    (4 / x).round(4)
  end

  def fx_2(x)
    ((5 + 6 * x - Math.sqrt(x**3)) / 12).round(4)
  end

  def f_12(x1, x2)
    (x1**3 - x2**3).round(4)
  end

  def f_21(x1, x2)
    (x1 + x2).round(4)
  end

  def generate_hash(params)
    arr = []
    x1_arr = numbers_array(params[:start_point], params[:end_point], params[:h1])
    x2_arr = numbers_array(params[:start_point], params[:end_point], params[:h2])
    fx = params[:fx]
    x1_arr.each do |x1|
      h = Hash.new
      x2_arr.each do |x_current|
        h.merge!({f_12(x1, x_current) => [x1, x_current]}) if fx == 12
        h.merge!({f_21(x1, x_current) => [x1, x_current]}) if fx == 21
      end
      min = h.keys.min
      min_x = h.select{|k, v| k == min}
      arr.push({x1: x1, x2: x2_arr, fx: h.keys, min_fx: min, min_fx_x1_x2: min_x })
    end
    arr
  end
end

app/views/dashboard/_first_tab.html.erb
<table class="table table-striped">
  <% @hash = Hash.new %>
  <% numbers_array(@start_point, @end_point, 0.001).each do |val| %>
      <tr>
        <td><%= val %></td>
        <td><%= val_1 = fx_1(val)%></td>
        <td><%= val_2 = fx_2(val) %></td>
        <% max = {val => [val_1, val_2].max} %>
        <td>MAX = <%= max.values.first %></td>
        <% @hash.merge!(max) %>
      </tr>
  <% end %>
</table>

<h1>MINIMUM value - <%= min_val = @hash.values.min %></h1>

<h3>X =<%= @hash.select{|k, v| v == min_val}.keys.uniq %></h3>

app/views/dashboard/_second_tab.html.erb
<table class="table table-striped">
  <% @hash = Hash.new %>
  <% numbers_array(@start_point, @end_point, 0.001).each_with_index do |val| %>
      <tr>
        <td><%= val %></td>
        <td><%= val_1 = fx_1(val)%></td>
        <td><%= val_2 = fx_2(val) %></td>
        <% min = {val => [val_1, val_2].min} %>
        <td>MIN = <%= min.values.first %></td>
        <% @hash.merge!(min) %>
      </tr>
  <% end %>
</table>

<h1>MAXIMUM value - <%= max_val = @hash.values.max %></h1>

<h3>X =<%= @hash.select{|k, v| v == max_val}.keys.uniq %></h3>

app/views/dashboard/_task_2_first_tab.html.erb
<% arr = generate_hash({start_point: 0, end_point: 4, h1: 0.2, h2: 0.1, fx: 12}) %>
<table class="table table-striped">
<tbody>
<% arr.each do |row| %>
    <tr>
      <td>X1</td>
      <td style="background: #ffc73a;"><%= row[:x1] %></td>
    </tr>
    <tr >
      <td>X2</td>
      <% row[:x2].each do |x2| %>
          <td style="background: #ff9575;"> <%= x2 %></td>
      <% end %>
    </tr>
    <tr>
      <td>F12(x)</td>
      <% row[:fx].each do |fx| %>
          <td> <%= fx %></td>
      <% end %>
    </tr>
    <tr>
      <td style="background: #2bff1d;">MIN</td>
      <td style="background: #2bff1d;"><%= row[:min_fx] %></td>
    </tr>
<% end %>
</tbody>
</table>
<h3>
  <% max_fx = arr.map{|hash| hash[:min_fx]}.max %>
  <%= arr.select{|hash| hash[:min_fx] == max_fx}.first[:min_fx_x1_x2] %>
</h3>
<hr>
<%= render 'dashboard/charts/task_2_first_tab_chart', stats: arr %>

app/views/dashboard/_task_2_second_tab.html.erb
<% arr = generate_hash({start_point: 0, end_point: 4, h1: 0.2, h2: 0.1, fx: 21}) %>
<table class="table table-striped">
  <tbody>
  <% arr.each do |row| %>
      <tr>
        <td>X2</td>
        <td style="background: #ffc73a;"><%= row[:x1] %></td>
      </tr>
      <tr >
        <td>X1</td>
        <% row[:x2].each do |x2| %>
            <td style="background: #ff9575;"> <%= x2 %></td>
        <% end %>
      </tr>
      <tr>
        <td>F12(x)</td>
        <% row[:fx].each do |fx| %>
            <td> <%= fx %></td>
        <% end %>
      </tr>
      <tr>
        <td style="background: #2bff1d;">MIN</td>
        <td style="background: #2bff1d;"><%= row[:min_fx] %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<h3>
  <% max_fx = arr.map{|hash| hash[:min_fx]}.max %>
  <%= arr.select{|hash| hash[:min_fx] == max_fx}.first[:min_fx_x1_x2] %>
</h3>
<hr>
<%= render 'dashboard/charts/task_2_second_tab_chart', stats: arr %>

app/views/dashboard/charts/_task_2_first_tab_chart.html.erb
<div id="container" style="height: 400px; min-width: 310px"></div>

<%= content_tag :div, class: "fx-12", data: {fx: stats.map{|h| h[:fx]}, ox: stats.first[:x2], x1: stats.map{|h| h[:x1]}} do %>
<% end %>
<%= javascript_include_tag 'stats_charts/task_2_stats' %>

app/views/dashboard/charts/_task_2_second_tab_chart.html.erb
<div id="container21" style="height: 700px; min-width: 510px"></div>

<%= content_tag :div, class: "fx-21", data: {fx: stats.map{|h| h[:fx]}, ox: stats.first[:x2], x1: stats.map{|h| h[:x1]}} do %>
<% end %>
<%= javascript_include_tag 'stats_charts/task_2_stats' %>

app/views/dashboard/index.html.erb
<%= link_to 'Задача №2', second_task_path %>
<h1>Задача №1</h1>
<hr>
<p><h3>F1(x) = 20 / 5x</h3></p>
<p><h3>F2(x) = (5 + 6x - sqrt(x^3)) / 12</h3></p>
<hr>
<p>  <h4>Start Point = 1.461</h4></p>
<p><h4>End Point = 4.000</h4></p>
<p><h4>step = 0.001</h4></p>
<br>
<div id="exTab22" class="container">
  <ul class="nav nav-tabs">
    <li class="active">
      <a  href="#1" data-toggle="tab">First step</a>
    </li>
    <li><a href="#2" data-toggle="tab">Second step</a>
    </li>
  </ul>
  <div class="tab-content ">
    <div class="tab-pane active" id="1">
      <%= render('first_tab') %>
    </div>
    <div class="tab-pane" id="2">
      <%= render('second_tab') %>
    </div>
  </div>
</div>
<hr>

app/views/dashboard/second_task.html.erb
<%= link_to 'Задача №1', root_path %>
<h1>Задача №2</h1>
<hr>
<p><h3>F12(x) = X1^3 - X2^3</h3></p>
<p><h3>F21(x) = X1 + X2</h3></p>
<hr>
<p>  <h4>Start Point = 0</h4></p>
<p><h4>End Point = 4</h4></p>
<p><h4>h1 = 1</h4></p>
<p><h4>h2 = 0.2</h4></p>
<br>
<div id="exTab2" class="container">
  <ul class="nav nav-tabs">
    <li class="active">
      <a  href="#3" data-toggle="tab">First step</a>
    </li>
    <li><a href="#4" data-toggle="tab">Second step</a>
    </li>
  </ul>

  <div class="tab-content ">
    <div class="tab-pane active" id="3">
      <%= render('task_2_first_tab') %>
    </div>
    <div class="tab-pane" id="4">
      <%= render('task_2_second_tab') %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TPRKarin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>